[package]
name = "ray-rust"
version = "0.1.0"
edition = "2021"
description = "spatie ray debugger"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
